name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "seanh/pelican/.github/workflows/github_pages.yml@gha-theme-support"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "pelicanconf.py"
      requirements: "-r requirements/dev.txt"
      theme: "https://github.com/seanh/sidecar.git"
